Make the completion script show why it cannot generate the completions.
Without that change, it is difficult to root-cause.

testing done:

~/WORK/mint_trunk/mint > (1) /Users/dnozay/WORK/mint_trunk/mint/build/venv/bin/python ~/WORK/gradle-python_trunk/gradle-python/src/main/resources/click_tabtab.py
ERROR: Cannot generate completions for mint; see stacktrace below.
\################################################################################
ERROR:root:No module named gen.com.linkedin.tools.events
Traceback (most recent call last):
  File "/Users/dnozay/WORK/gradle-python_trunk/gradle-python/src/main/resources/click_tabtab.py", line 366, in main
    ep = entrypoint.load()
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/dnozay/WORK/mint_trunk/mint/src/mint/main.py", line 42, in <module>
    from linkedin.mint import main as mintmain, publish, mplint, build, dependencies, scm
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/linkedin/mint/publish.py", line 35, in <module>
    from pegasus.gen.com.linkedin.tools.events import MPArtifactPublishEvent
ImportError: No module named gen.com.linkedin.tools.events
\################################################################################
ERROR: Cannot generate completions for mint-integration; see stacktrace below.
\################################################################################
ERROR:root:No module named gen
Traceback (most recent call last):
  File "/Users/dnozay/WORK/gradle-python_trunk/gradle-python/src/main/resources/click_tabtab.py", line 366, in main
    ep = entrypoint.load()
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/dnozay/WORK/mint_trunk/mint/src/mint/integration.py", line 28, in <module>
    from linkedin.mint.integfwk.services import TestServiceControl, SeleniumTestControl
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/linkedin/mint/integfwk/services.py", line 22, in <module>
    from linkedin.deployment.helpers.mint import deploy_product, undeploy_product
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/linkedin/deployment/helpers/mint.py", line 9, in <module>
    from linkedin.deployment.control import ControlDeploymentManager
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/linkedin/deployment/control/__init__.py", line 21, in <module>
    from linkedin.deployment.control.backends.lid import LID
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/linkedin/deployment/control/backends/lid.py", line 17, in <module>
    from linkedin.deployment.lid.salt import SaltBasedBatchWorker, SaltBasedRequestWorker, SaltBasedPlanWorker
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/linkedin/deployment/lid/salt.py", line 17, in <module>
    from linkedin.deployment.lid.batch import DeploymentRequestBatchWorker
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/linkedin/deployment/lid/batch.py", line 12, in <module>
    from linkedin.deployment.client import DeploymentProcessorAction
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/linkedin/deployment/client.py", line 30, in <module>
    from linkedin.deployment.request import DeploymentRequest
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/linkedin/deployment/request.py", line 14, in <module>
    from linkedin.crt.types import DeploymentEventType
  File "/Users/dnozay/WORK/mint_trunk/mint/build/venv/lib/python2.6/site-packages/linkedin/crt/__init__.py", line 2, in <module>
    import pegasus.gen  # noqa
ImportError: No module named gen
\################################################################################
Did not find a Click command to generate completions for.

RB=645126
R=zpetkovi,xachen,dholman,psantann,sholsapp,ethall
A=zpetkovi